"""
Institutional Confluence Engine
Evaluates alignments between Volume Zones and Gamma Levels.
"""
import logging
from dataclasses import dataclass
from typing import List, Optional, Tuple

from core.volume.zone_engine import InstitutionalZone
from core.intelligence.gamma_engine import GammaState

@dataclass
class ConfluenceReport:
    """Report generated by the ConfluenceEngine."""
    score: int                  # 0 to 100
    is_tradeable: bool          # Score >= threshold
    reasons: List[str]          # Breakdown of points
    zone_aligned: bool          # Is price at a volume zone?
    gamma_aligned: bool         # Is gamma structure supportive?
    
    def to_dict(self) -> dict:
        return {
            "score": self.score,
            "is_tradeable": self.is_tradeable,
            "reasons": self.reasons,
            "zone_aligned": self.zone_aligned,
            "gamma_aligned": self.gamma_aligned
        }

class ConfluenceEngine:
    """
    Scores entries based on multiple institutional data sources.
    
    Scoring Logic (Max 100):
    1. Base Score (Max 50): Price is interacting with an InstitutionalZone
    2. Gamma Alignment (Max 25): Gamma state supports the trade direction
    3. Proximity Precision (Max 25): How exact the spot price is to key levels
    
    Deductions (-50): Conflicting setups (e.g., Shorting in positive gamma away from resistance)
    """
    
    def __init__(self, required_threshold: int = 70):
        self.logger = logging.getLogger("ConfluenceEngine")
        self.required_threshold = required_threshold
        
    def evaluate(
        self,
        spot_price: float,
        direction: str,  # "LONG" or "SHORT" (or "BULLISH", "BEARISH")
        active_zones: List[InstitutionalZone],
        gamma_state: Optional[GammaState]
    ) -> ConfluenceReport:
        """Evaluate market confluence at current spot price."""
        score = 0
        reasons = []
        zone_aligned = False
        gamma_aligned = False
        
        dir_clean = "LONG" if direction.upper() in ["LONG", "BULLISH", "CALL"] else "SHORT"
        
        # 1. Volume Zone Base Score (Max 50)
        nearest_zone = self._find_nearest_zone(spot_price, active_zones)
        zone_score, zone_reason, is_inside = self._evaluate_zone(spot_price, nearest_zone)
        
        score += zone_score
        if zone_reason:
            reasons.append(zone_reason)
        zone_aligned = is_inside
            
        # 2. Gamma Alignment (Max 25)
        gamma_score, gamma_reason, is_gamma_aligned = self._evaluate_gamma(spot_price, dir_clean, gamma_state)
        
        score += gamma_score
        if gamma_reason:
            reasons.append(gamma_reason)
        gamma_aligned = is_gamma_aligned
            
        # 3. Proximity Precision (Max 25)
        prox_score, prox_reason = self._evaluate_proximity(spot_price, nearest_zone, gamma_state)
        score += prox_score
        if prox_reason:
            reasons.append(prox_reason)
            
        # 4. Deductions for conflicts
        deduction, ded_reason = self._evaluate_conflicts(spot_price, dir_clean, is_inside, gamma_state)
        if deduction > 0:
            score -= deduction
            reasons.append(f"DEDUCTION (-{deduction}): {ded_reason}")
            
        # Final formatting
        score = max(0, min(100, score))  # Clamp between 0 and 100
        is_tradeable = score >= self.required_threshold
        
        return ConfluenceReport(
            score=score,
            is_tradeable=is_tradeable,
            reasons=reasons,
            zone_aligned=zone_aligned,
            gamma_aligned=gamma_aligned
        )
        
    def _find_nearest_zone(self, price: float, zones: List[InstitutionalZone]) -> Optional[InstitutionalZone]:
        if not zones:
            return None
        return min(zones, key=lambda z: abs(z.poc - price))
        
    def _evaluate_zone(self, spot: float, zone: Optional[InstitutionalZone]) -> Tuple[int, str, bool]:
        if not zone:
            return 0, "No active volume zones nearby.", False
            
        if zone.contains(spot):
            pts = 50 if zone.is_fresh else 30
            fresh_str = "FRESH" if zone.is_fresh else "RETEST"
            return pts, f"+{pts}: Price inside {fresh_str} Institutional Zone (POC: {zone.poc:.2f}).", True
            
        # Close but not inside
        dist = abs(spot - zone.poc)
        prox_pct = dist / spot
        if prox_pct < 0.005: # Within 0.5%
            return 10, "+10: Price approaching Institutional Zone.", False
            
        return 0, "Price is far from active volume zones.", False
        
    def _evaluate_gamma(self, spot: float, direction: str, state: Optional[GammaState]) -> Tuple[int, str, bool]:
        if not state or state.timestamp == 0:
            return 0, "Gamma state unavailable.", False
            
        score = 0
        reason = ""
        aligned = False
        
        if direction == "LONG":
            # Longs favor negative gamma (expansion/reversion) or pinning at max pain from below
            if state.zone == "NEGATIVE":
                score = 25
                reason = "+25: NEGATIVE Gamma (Expansion) supports directional long."
                aligned = True
            elif spot < state.max_pain and state.zone == "POSITIVE":
                # Price is below max pain, and market is in pinning regime. Market makers will buy dips.
                score = 20
                reason = "+20: POSITIVE Gamma (Pinning) with price < Max Pain. Dealers buying dips."
                aligned = True
        else: # SHORT
            # Shorts favor negative gamma (expansion) for crashes, or pinning from above
            if state.zone == "NEGATIVE":
                score = 25
                reason = "+25: NEGATIVE Gamma (Expansion) supports explosive downside."
                aligned = True
            elif spot > state.max_pain and state.zone == "POSITIVE":
                score = 20
                reason = "+20: POSITIVE Gamma (Pinning) with price > Max Pain. Dealers selling rallies."
                aligned = True
                
        if score == 0:
            reason = f"Gamma regime ({state.zone}) does not strongly support {direction} direction."
            
        return score, reason, aligned

    def _evaluate_proximity(self, spot: float, zone: Optional[InstitutionalZone], state: Optional[GammaState]) -> Tuple[int, str]:
        # Gives bonus precision points if spot is exactly on the POC or exact Gamma Flip line
        score = 0
        reasons = []
        
        if zone:
            # Within 0.1% of POC
            if abs(spot - zone.poc) / spot <= 0.001:
                score += 15
                reasons.append("+15: Sniper proximity to Volume POC.")
                
        if state and state.gamma_flip > 0:
            if abs(spot - state.gamma_flip) / spot <= 0.001:
                score += 10
                reasons.append("+10: Sniper proximity to Gamma Flip level.")
                
        reason_str = " / ".join(reasons) if reasons else ""
        return min(25, score), reason_str

    def _evaluate_conflicts(self, spot: float, direction: str, zone_inside: bool, state: Optional[GammaState]) -> Tuple[int, str]:
        if not state:
            return 0, ""
            
        # Example conflict: Shorting into a strong POSITIVE gamma regime when NOT at a resistance zone
        if direction == "SHORT" and state.zone == "POSITIVE" and not zone_inside:
            return 30, "Shorting into Pinning (Positive Gamma) without Zone Resistance."
            
        # Example conflict: Trading away from Max Pain in a POSITIVE pinning regime
        # Check if spot is defined in current scope
        if state.zone == "POSITIVE" and abs(spot - state.max_pain) / state.max_pain > 0.01:
            # It's an issue if we're betting on expansion in a pinning regime
             return 20, "Betting on trend in a strong POSITIVE Gamma (Pinning) regime."
             
        return 0, ""

# Singleton
confluence_engine = ConfluenceEngine()
